module.exports = {
  ALL_EXISTING_USERS_AT_CREATION: 'ALL_EXISTING_USERS_AT_CREATION',
  ALL_EXISTING_USERS_AFTER_CREATION: 'ALL_EXISTING_USERS_AFTER_CREATION',
  ALL_PAST_AND_FUTURE_USERS: 'ALL_PAST_AND_FUTURE_USERS',
  CUSTOM: 'CUSTOM',
};
